config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :most_recent_guess,
            presence: true, if: proc { |c| !c.guesses.blank? }, # TODO: this is horrible - intent is to only validate for games already in progress and guesses being blank is at best coincidentally true when this is a new game
            format: { with: /([A-Za-z])/, message: 'You can only guess alphabetic characters' }
  validate :already_guessed

  attr_accessor :most_recent_guess # TODO: it feels a bit wrong to have this transient property on Game at all. Is it?

  # TODO would prefer to validate with a custom validator but couldn't get one to work ' could not find such file ' and so forth
  def already_guessed
    there_is_a_guess = !most_recent_guess.blank?
    if (there_is_a_guess and guesses.include? most_recent_guess)
      errors.add(:most_recent_guess, "You've already guessed #{most_recent_guess}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new(word_to_be_guessed: 'hello', guesses: [])
  end

  # GET /games/1/edit
  def edit; end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|

      if @game.valid?
        @game.guesses << @game.most_recent_guess
        @game.most_recent_guess = ''

        # TODO figure out how much of this stuff is needed
        if @game.update(game_params)
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { render :show, status: :ok, location: @game }
        else
          format.html { render :edit }
          format.json { render json: @game.errors, status: :unprocessable_entity }
          end
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:word_to_be_guessed, :guesses, :most_recent_guess)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def clue(game)
    clue_string = game.word_to_be_guessed.chars
                      .map { |char| game.guesses.include?(char) ? char : '_' }
                      .join
    word_length = game.word_to_be_guessed.size
    "#{clue_string} (#{word_length} letters)"
  end

  def guesses_for_display(game)
    game.guesses.chars.join(',')
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= clue(game) %>
  </div>

    <%= form.hidden_field :word_to_be_guessed %>
    <%= form.hidden_field :guesses %>

    <!-- TODO don't show this on a new game screen -->
  <div class="field">
    <%= guesses_for_display(game) %>
  </div>

  <div class="field">
    <%= form.label 'New guess' %>
    <%= form.text_field :most_recent_guess %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Word to be guessed</th>
      <th>Guesses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= clue(game) %></td>
        <td><%= game.guesses %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clue:</strong>
  <%= clue(@game) %>
</p>

<p>
  <strong>Guesses:</strong>
  <%= @game.guesses %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HangmanRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>